### ISSUE TITLE
Integration timesout on initializing and becomes inactive for long periods

### ISSUE THREAD

**Issue by povinhox** [tggm/rointe-radiators#18]
Hi,

Rointe-HACS Version: [V1.6.0-b0]

Home Assistant
 Core 2024.11.2
 Supervisor 2024.11.2
 Operating System 13.2
 Frontend 20241106.2

Since a month ago the integration timesout on initializing after HA restarts. Then after along time starts working. Then becomes inactive for long periods of time and comes back later.
Not sure if Rointe is blocking HA frequent requests for data.

During Rointe integration inactive moments is impossible for the automations to work. 

I hope you can help. Thanking you in advance.

Errors found on the log:
This shows several times:
`2024-11-21 21:22:27.167 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: {('rointe', 'e934a991e7afaff9a3570408a33e5ad5'): 60.269347179}`

There is also this:
`2024-11-21 21:26:28.895 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Lisboa, Portugal for rointe
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rointe/__init__.py", line 38, in async_setup_entry
    await rointe_coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 309, in async_config_entry_first_refresh
    await self._async_refresh(
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rointe/coordinator.py", line 64, in _async_update_data
    new_devices = await self.device_manager.update()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rointe/device_manager.py", line 147, in update
    await asyncio.gather(*pending_futures)
asyncio.exceptions.CancelledError: Global task timeout
2024-11-21 21:26:28.909 WARNING (MainThread) [homeassistant.bootstrap] Setup timed out for stage 2 waiting on set() - moving forward
`

**Comment by povinhox** [comment]
This issue actually got better the last few days. I think ROINTE is just timing out some of the requests and not all. I'm adding the temperature graph of one of the Radiators where you can see sections missing. This happens when becomes inactive. So! Maybe we need to reduce the update frequency.

![Captura de ecrã 2024-12-03 185030](https://github.com/user-attachments/assets/75fd310a-998c-4291-8928-2999008079c0)

**Comment by tggm** [comment]
Hi @povinhox, The code changed quite a bit with version v2.0.0. Are you still seeing the same behavior ?

**Comment by povinhox** [comment]
Hi tggm,
Actually it started working fine again after I've reinstalled version 1.6.1. I was going to close this issues.
But! Now I've tried 2.1.0 and it duplicated the entities with in each device. The Devices remained but it inactivated the entity I had configure and added a new one. See screenshot.
It's this expected and I need to replace all my Dashboards and Rules or there will be a fix? I tried to go back to 1.6.1 but now I can only see 1.4.3.... Any advise?nThank you,

![image](https://github.com/user-attachments/assets/44359ed6-d05f-47a5-8219-d8b96470d16c)
![image](https://github.com/user-attachments/assets/e55ec7ea-057d-42ae-abde-983ff2efcba9)

**Comment by povinhox** [comment]
I found a fix! I've removed the integration and added it again. And now I have the Devices with the original Name and the correct number of entities.
![image](https://github.com/user-attachments/assets/dd49ae2c-8253-4a49-a315-f728100b720d)
Thank you for all your work. I'll monitor if the connection stays stable.

**Comment by tggm** [comment]
This may have been caused by some changed the HA maintainers recommended for the integration. I remember changes in the entity naming.

I updated the Readme with a note to uninstall prior versions to 2.0.0

Thank you once again!
